[package]
name = "volumen"
version = "1.2.0"
authors = ["Spyros Roum <spyrosr1@gmail.com>"]
edition = "2018"
description = "Command line pastebin for sharing terminal output. "
readme = "README.md"
repository = "https://github.com/SpyrosRoum/volumen"
license-file = "LICENSE"
categories = ["command-line-utilities"]

[dependencies]
structopt = "0.3"
anyhow = "1"
rand = "0.8"
simplelog = "0.9"
log = "0.4"
dirs-next = "2"

rocket = { version = "0.4", default_features = false }
askama = "0.8"
zstd = "0.6"
