[package]
name = "termpad"
version = "0.1.0"
authors = ["Spyros Roum <spyrosr1@gmail.com>"]
edition = "2018"
description = "Command line pastebin for sharing terminal output. "
readme = "README.md"
repository = "https://github.com/SpyrosRoum/termpad"
license-file = "LICENSE"
categories = ["command-line-utilities"]

[features]
default = []
web = ["warp", "tokio", "askama"]

[dependencies]
structopt = "0.3"
anyhow = "1"
rand = "0.8"

warp = { version = "0.3", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
askama = { version = "0.8", optional = true }
