version: "3.4"

services:
  app:
    image: aindoria/volumen
    ports:
      - 8005:8000
    environment:
      - DOMAIN_NAME=volumen.civitat.es # You probably want to change this
      - HTTPS=true
      - DELETE_AFTER=120 # If you are hosting for yourself keeping them forever is probably fine
    volumes:
      - ./data:$HOME/.local/share/volumen/
    restart: always

